#!/usr/bin/env php
<?php

declare(strict_types=1);

require __DIR__ . '/config/env.php';

defined('YII_DEBUG') or define('YII_DEBUG', (getenv('YII_DEBUG') ?: 'true') === 'true');
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV') ?: 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$exitCode = (new yii\console\Application($config))->run();
exit($exitCode);
